CREATE TABLE PRODUTO_PRECO(
    ID NUMBER PRIMARY KEY,
    ID_PRODUTO NUMBER,
    VALOR NUMBER(10, 2),
    STATUS NUMBER(1),
    CADASTRO DATE,
    CONSTRAINT fk_produto_preco FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID)
);