BEGIN
    FOR I IN (SELECT * FROM PRODUTO) LOOP
        IF I.STATUS = 1 THEN
            DBMS_OUTPUT.PUT_LINE('PRODUTO: '||I.DESCRICAO||' - STATUS: ATIVO');
        ELSE
            DBMS_OUTPUT.PUT_LINE('PRODUTO: '||I.DESCRICAO||' - STATUS: DESATIVADO');
        END IF;
    END LOOP;
END;